pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        String result='0.0.0';
    }
    stages {
        stage('Git Checkout'){
            steps{
                checkout([$class: 'GitSCM', 
                branches: [[name: '*/tags/*']], 
                extensions: [[$class: 'PerBuildTag']], 
                userRemoteConfigs: [[credentialsId: 'jenkins-git-ssh', 
                refspec: '+refs/tags/*:refs/remotes/origin/tags/*', 
                url: 'https://github.com/poojarampariya/simple-java-maven-app.git']]])
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                // sh "git tag build_${gitCommit}"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
